### ISSUE TITLE
Speed parsing truncates decimal values

### ISSUE THREAD

**Issue by maninhighcastle** [spencermehta/automated-speedtests#2]
If the speed is 100 Mbps or greater, the decimal values are truncated due to the static string splicing.

I've made this my personal version which is dynamic:
`first_space = lines[0].find(' ') + 1`
`p = lines[0][first_space:lines[0].find(' ',first_space)]`
`first_space = lines[1].find(' ') + 1`
`d = lines[1][first_space:lines[0].find(' ',first_space)]`
`first_space = lines[2].find(' ') + 1`
`u = lines[2][first_space:lines[0].find(' ',first_space)]`

**Comment by spencermehta** [comment]
Good find. I've now fixed this by changing the code to the following:
```
p = lines[0].split(' ')[1]
d = lines[1].split(' ')[1]
u = lines[2].split(' ')[1]
```

**Comment by maninhighcastle** [comment]
derp, can't believe i added so much overhead to my parse. That's a much more elegant solution.
