### ISSUE TITLE
ppa:fkrull/deadsnakes pre-requisites on OS X?

### ISSUE THREAD

**Issue by brianjking** [spencermehta/automated-speedtests#4]
`Python 3.5 - add-apt-repository ppa:fkrull/deadsnakes, apt-get update, apt-get install python3.5`

What is this module used for and is there a way to install it that you know of outside of apt-get for running it on OS X?

Thanks!

**Comment by spencermehta** [comment]
This is simply to install Python 3.5. 
Scroll to the bottom of [this page](https://www.python.org/downloads/release/python-351/) to find the downloads, although by the look of your other comments you've already solved this.
