### ISSUE TITLE
Collaborator Access for Wiki Pages

### ISSUE THREAD

**Issue by brianjking** [spencermehta/automated-speedtests#6]
Hi,

I'd like to provide a wiki page for using this with NGINX as that's my preferred service and it's definitely super lightweight for use on a device such as a RaspberryPi, which is where I'm hosting my instance of your speedtest script at.

Can you add me as a collaborator on your project?

Thanks!

**Comment by spencermehta** [comment]
Sure

**Comment by spencermehta** [comment]
I have now simply added instructions to the main installation guide giving the reader the option to use either apache2 or nginx
