### ISSUE TITLE
systemd conf in wiki is invalid

### ISSUE THREAD

**Issue by sethrd** [spencermehta/automated-speedtests#9]
Using the service file provided in the wiki did not allow the service to start, even though starting it manually ( in screen or otherwise ) worked perfectly fine. It was giving the following error:

```
Aug 31 10:33:27 host python3[2559]: Traceback (most recent call last):
Aug 31 10:33:27 host python3[2559]: File "/path/to/automated-speedtests/automated-speedtests.py", line 29, in <module>
Aug 31 10:33:27 host python3[2559]: with open('config.json', 'r') as f:
Aug 31 10:33:27 host python3[2559]: FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
Aug 31 10:33:27 host systemd[1]: speedtest.service: main process exited, code=exited, status=1/FAILURE
Aug 31 10:33:27 host systemd[1]: Unit speedtest.service entered failed state.
Aug 31 10:33:27 host systemd[1]: speedtest.service failed.
```

To correct this, I had to modify the automated-speedtests.py to have the full path to config.json:

```
with open('/path/to/automated-speedtests/config.json', 'r') as f:
        config = json.load(f)
```

Once that was done, the service was able to start without issue.

**Comment by meowimacow** [comment]
Yes I had noticed this issue during development with the `speedtest` and `webserver` paths so I added a note to the wiki about it.  

Unfortunately you are unable to provide a full path for `config.json` without modifying the code itself, unlike the other two which were accessible in the config file.  

I've been able to resolve this issue by appending `WorkingDirectory=/path/to/automated-speedtests/` to the `[Service]` section of the systemd service config, also removing the need for full paths to the `speedtest` and `webserver` directories.  

If you would like to check that this solution also works for you then I can mark the issue as resolved :)

**Comment by sethrd** [comment]
Didn't even think of using WorkingDirectory in the systemd service file. Reverted the changes to automated-speedtests.py, added WorkingDirectory, and service restarts fine. I see that the wiki has also been updated.  Feel free to mark resolved.
